
# Logical operators are another type of boolean operator (True/False)
print("True and True == ", True and True)
print("True and False == ", True and False)
print("True or True == ", True or True)
print("False or False == ", False or False)
print("not True == ", not True)
print("not False == ", not False)
print("\nFor Example: ")
print("not 1 == 2 and 2 == 2 and 5 < 10", not 1 == 2 and 2 == 2 and 5 < 10)
print("")
